/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.formatting2;

import com.google.inject.Inject;
import java.util.Arrays;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;
import org.xtext.example.mydsl.services.MyDslGrammarAccess;
import xPDL.Lane;
import xPDL.MessageFlow;
import xPDL.Pool;
import xPDL.XpdlRoot;

@SuppressWarnings("all")
public class MyDslFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private MyDslGrammarAccess _myDslGrammarAccess;

  protected void _format(final XpdlRoot xpdlRoot, @Extension final IFormattableDocument document) {
    EList<Pool> _pools = xpdlRoot.getPools();
    for (final Pool pool : _pools) {
      document.<Pool>format(pool);
    }
    EList<xPDL.Process> _process = xpdlRoot.getProcess();
    for (final xPDL.Process process : _process) {
      document.<xPDL.Process>format(process);
    }
    EList<MessageFlow> _messageflows = xpdlRoot.getMessageflows();
    for (final MessageFlow messageFlow : _messageflows) {
      document.<MessageFlow>format(messageFlow);
    }
  }

  protected void _format(final Pool pool, @Extension final IFormattableDocument document) {
    EList<Lane> _lanes = pool.getLanes();
    for (final Lane lane : _lanes) {
      document.<Lane>format(lane);
    }
  }

  public void format(final Object pool, final IFormattableDocument document) {
    if (pool instanceof XtextResource) {
      _format((XtextResource)pool, document);
      return;
    } else if (pool instanceof Pool) {
      _format((Pool)pool, document);
      return;
    } else if (pool instanceof XpdlRoot) {
      _format((XpdlRoot)pool, document);
      return;
    } else if (pool instanceof EObject) {
      _format((EObject)pool, document);
      return;
    } else if (pool == null) {
      _format((Void)null, document);
      return;
    } else if (pool != null) {
      _format(pool, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(pool, document).toString());
    }
  }
}
