<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="xPDL" nsURI="http://www.example.com/xpdl" nsPrefix="xPDL">
  <eClassifiers xsi:type="ecore:EClass" name="XpdlRoot">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pools" upperBound="-1"
        eType="#//Pool" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="process" upperBound="-1"
        eType="#//Process" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="messageflows" upperBound="-1"
        eType="#//MessageFlow" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diagramName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pool" eSuperTypes="#//AssociationValid #//MessageFlowValid">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lanes" lowerBound="1" upperBound="-1"
        eType="#//Lane" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Lane" eSuperTypes="#//AssociationValid">
    <eStructuralFeatures xsi:type="ecore:EReference" name="activityset" eType="#//ActivitySet"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivitySet">
    <eStructuralFeatures xsi:type="ecore:EReference" name="activities" lowerBound="1"
        upperBound="-1" eType="#//Activity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Process">
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitions" upperBound="-1"
        eType="#//Transition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activityset" upperBound="-1"
        eType="#//ActivitySet" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pool" lowerBound="1" eType="#//Pool"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Activity" eSuperTypes="#//AssociationValid #//MessageFlowValid #//TransitionValid">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BlockActivity" eSuperTypes="#//Activity"/>
  <eClassifiers xsi:type="ecore:EClass" name="Event" eSuperTypes="#//Activity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="time" eType="#//EventTime"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//EventType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Gateway" eSuperTypes="#//Activity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rule" eType="#//GateRule"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubFlow" eSuperTypes="#//Activity"/>
  <eClassifiers xsi:type="ecore:EEnum" name="EventTime">
    <eLiterals name="START"/>
    <eLiterals name="INTERMEDIATE" value="1"/>
    <eLiterals name="END" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Artifact" eSuperTypes="#//AssociationValid"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataObject" eSuperTypes="#//Artifact"/>
  <eClassifiers xsi:type="ecore:EClass" name="AssociationValid" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="TransitionValid" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="MessageFlowValid" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="MessageFlow">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//MessageFlowValid"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//MessageFlowValid"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Association">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//AssociationValid"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//AssociationValid"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition" eSuperTypes="#//AssociationValid">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//TransitionValid"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//TransitionValid"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EventType">
    <eLiterals name="NONE" literal="NONE"/>
    <eLiterals name="MESSAGE" value="1"/>
    <eLiterals name="EROR" value="2"/>
    <eLiterals name="RULE" value="3"/>
    <eLiterals name="TIMER" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GateRule">
    <eLiterals name="XOR"/>
    <eLiterals name="OR" value="1"/>
    <eLiterals name="AND" value="2"/>
  </eClassifiers>
</ecore:EPackage>
