/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class MyDslGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class XpdlRootElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.XpdlRoot");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cXpdlRootAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cXpdlRootKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cIdAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cIdEStringParserRuleCall_2_0 = (RuleCall)cIdAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDiagramNameKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cDiagramNameAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cDiagramNameEStringParserRuleCall_4_1_0 = (RuleCall)cDiagramNameAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cPoolsKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cPoolsAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cPoolsPoolParserRuleCall_5_2_0 = (RuleCall)cPoolsAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cPoolsAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cPoolsPoolParserRuleCall_5_3_1_0 = (RuleCall)cPoolsAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cProcessKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cProcessAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cProcessProcessParserRuleCall_6_2_0 = (RuleCall)cProcessAssignment_6_2.eContents().get(0);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cProcessAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final RuleCall cProcessProcessParserRuleCall_6_3_1_0 = (RuleCall)cProcessAssignment_6_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cMessageflowsKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cMessageflowsAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cMessageflowsMessageFlowParserRuleCall_7_2_0 = (RuleCall)cMessageflowsAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cMessageflowsAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final RuleCall cMessageflowsMessageFlowParserRuleCall_7_3_1_0 = (RuleCall)cMessageflowsAssignment_7_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//XpdlRoot returns XpdlRoot:
		//    {XpdlRoot}
		//    'XpdlRoot'
		//    id=EString
		//    '{'
		//        ('diagramName' diagramName=EString)?
		//        ('pools' '{' pools+=Pool ( "," pools+=Pool)* '}' )?
		//        ('process' '{' process+=Process ( "," process+=Process)* '}' )?
		//        ('messageflows' '{' messageflows+=MessageFlow ( "," messageflows+=MessageFlow)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{XpdlRoot}
		//'XpdlRoot'
		//id=EString
		//'{'
		//    ('diagramName' diagramName=EString)?
		//    ('pools' '{' pools+=Pool ( "," pools+=Pool)* '}' )?
		//    ('process' '{' process+=Process ( "," process+=Process)* '}' )?
		//    ('messageflows' '{' messageflows+=MessageFlow ( "," messageflows+=MessageFlow)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{XpdlRoot}
		public Action getXpdlRootAction_0() { return cXpdlRootAction_0; }
		
		//'XpdlRoot'
		public Keyword getXpdlRootKeyword_1() { return cXpdlRootKeyword_1; }
		
		//id=EString
		public Assignment getIdAssignment_2() { return cIdAssignment_2; }
		
		//EString
		public RuleCall getIdEStringParserRuleCall_2_0() { return cIdEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('diagramName' diagramName=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'diagramName'
		public Keyword getDiagramNameKeyword_4_0() { return cDiagramNameKeyword_4_0; }
		
		//diagramName=EString
		public Assignment getDiagramNameAssignment_4_1() { return cDiagramNameAssignment_4_1; }
		
		//EString
		public RuleCall getDiagramNameEStringParserRuleCall_4_1_0() { return cDiagramNameEStringParserRuleCall_4_1_0; }
		
		//('pools' '{' pools+=Pool ( "," pools+=Pool)* '}' )?
		public Group getGroup_5() { return cGroup_5; }
		
		//'pools'
		public Keyword getPoolsKeyword_5_0() { return cPoolsKeyword_5_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }
		
		//pools+=Pool
		public Assignment getPoolsAssignment_5_2() { return cPoolsAssignment_5_2; }
		
		//Pool
		public RuleCall getPoolsPoolParserRuleCall_5_2_0() { return cPoolsPoolParserRuleCall_5_2_0; }
		
		//( "," pools+=Pool)*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//pools+=Pool
		public Assignment getPoolsAssignment_5_3_1() { return cPoolsAssignment_5_3_1; }
		
		//Pool
		public RuleCall getPoolsPoolParserRuleCall_5_3_1_0() { return cPoolsPoolParserRuleCall_5_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }
		
		//('process' '{' process+=Process ( "," process+=Process)* '}' )?
		public Group getGroup_6() { return cGroup_6; }
		
		//'process'
		public Keyword getProcessKeyword_6_0() { return cProcessKeyword_6_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_6_1() { return cLeftCurlyBracketKeyword_6_1; }
		
		//process+=Process
		public Assignment getProcessAssignment_6_2() { return cProcessAssignment_6_2; }
		
		//Process
		public RuleCall getProcessProcessParserRuleCall_6_2_0() { return cProcessProcessParserRuleCall_6_2_0; }
		
		//( "," process+=Process)*
		public Group getGroup_6_3() { return cGroup_6_3; }
		
		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }
		
		//process+=Process
		public Assignment getProcessAssignment_6_3_1() { return cProcessAssignment_6_3_1; }
		
		//Process
		public RuleCall getProcessProcessParserRuleCall_6_3_1_0() { return cProcessProcessParserRuleCall_6_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6_4() { return cRightCurlyBracketKeyword_6_4; }
		
		//('messageflows' '{' messageflows+=MessageFlow ( "," messageflows+=MessageFlow)* '}' )?
		public Group getGroup_7() { return cGroup_7; }
		
		//'messageflows'
		public Keyword getMessageflowsKeyword_7_0() { return cMessageflowsKeyword_7_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }
		
		//messageflows+=MessageFlow
		public Assignment getMessageflowsAssignment_7_2() { return cMessageflowsAssignment_7_2; }
		
		//MessageFlow
		public RuleCall getMessageflowsMessageFlowParserRuleCall_7_2_0() { return cMessageflowsMessageFlowParserRuleCall_7_2_0; }
		
		//( "," messageflows+=MessageFlow)*
		public Group getGroup_7_3() { return cGroup_7_3; }
		
		//","
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }
		
		//messageflows+=MessageFlow
		public Assignment getMessageflowsAssignment_7_3_1() { return cMessageflowsAssignment_7_3_1; }
		
		//MessageFlow
		public RuleCall getMessageflowsMessageFlowParserRuleCall_7_3_1_0() { return cMessageflowsMessageFlowParserRuleCall_7_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7_4() { return cRightCurlyBracketKeyword_7_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class MessageFlowValidElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.MessageFlowValid");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cPoolParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cActivity_ImplParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cBlockActivityParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cEventParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cGatewayParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cSubFlowParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		
		//MessageFlowValid returns MessageFlowValid:
		//    Pool | Activity_Impl | BlockActivity | Event | Gateway | SubFlow;
		@Override public ParserRule getRule() { return rule; }
		
		//Pool | Activity_Impl | BlockActivity | Event | Gateway | SubFlow
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Pool
		public RuleCall getPoolParserRuleCall_0() { return cPoolParserRuleCall_0; }
		
		//Activity_Impl
		public RuleCall getActivity_ImplParserRuleCall_1() { return cActivity_ImplParserRuleCall_1; }
		
		//BlockActivity
		public RuleCall getBlockActivityParserRuleCall_2() { return cBlockActivityParserRuleCall_2; }
		
		//Event
		public RuleCall getEventParserRuleCall_3() { return cEventParserRuleCall_3; }
		
		//Gateway
		public RuleCall getGatewayParserRuleCall_4() { return cGatewayParserRuleCall_4; }
		
		//SubFlow
		public RuleCall getSubFlowParserRuleCall_5() { return cSubFlowParserRuleCall_5; }
	}
	public class ActivityElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Activity");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cActivity_ImplParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cBlockActivityParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cEventParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cGatewayParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cSubFlowParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		
		//Activity returns Activity:
		//    Activity_Impl | BlockActivity | Event | Gateway | SubFlow;
		@Override public ParserRule getRule() { return rule; }
		
		//Activity_Impl | BlockActivity | Event | Gateway | SubFlow
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Activity_Impl
		public RuleCall getActivity_ImplParserRuleCall_0() { return cActivity_ImplParserRuleCall_0; }
		
		//BlockActivity
		public RuleCall getBlockActivityParserRuleCall_1() { return cBlockActivityParserRuleCall_1; }
		
		//Event
		public RuleCall getEventParserRuleCall_2() { return cEventParserRuleCall_2; }
		
		//Gateway
		public RuleCall getGatewayParserRuleCall_3() { return cGatewayParserRuleCall_3; }
		
		//SubFlow
		public RuleCall getSubFlowParserRuleCall_4() { return cSubFlowParserRuleCall_4; }
	}
	public class TransitionValidElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.TransitionValid");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cActivity_ImplParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cBlockActivityParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cEventParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cGatewayParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cSubFlowParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		
		//TransitionValid returns TransitionValid:
		//    Activity_Impl | BlockActivity | Event | Gateway | SubFlow;
		@Override public ParserRule getRule() { return rule; }
		
		//Activity_Impl | BlockActivity | Event | Gateway | SubFlow
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Activity_Impl
		public RuleCall getActivity_ImplParserRuleCall_0() { return cActivity_ImplParserRuleCall_0; }
		
		//BlockActivity
		public RuleCall getBlockActivityParserRuleCall_1() { return cBlockActivityParserRuleCall_1; }
		
		//Event
		public RuleCall getEventParserRuleCall_2() { return cEventParserRuleCall_2; }
		
		//Gateway
		public RuleCall getGatewayParserRuleCall_3() { return cGatewayParserRuleCall_3; }
		
		//SubFlow
		public RuleCall getSubFlowParserRuleCall_4() { return cSubFlowParserRuleCall_4; }
	}
	public class PoolElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Pool");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPoolKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cIdAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cIdEStringParserRuleCall_1_0 = (RuleCall)cIdAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cNameKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cNameAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_3_1_0 = (RuleCall)cNameAssignment_3_1.eContents().get(0);
		private final Keyword cLanesKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cLeftCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cLanesAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cLanesLaneParserRuleCall_6_0 = (RuleCall)cLanesAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cCommaKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cLanesAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cLanesLaneParserRuleCall_7_1_0 = (RuleCall)cLanesAssignment_7_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//Pool returns Pool:
		//    'Pool'
		//    id=EString
		//    '{'
		//        ('name' name=EString)?
		//        'lanes' '{' lanes+=Lane ( "," lanes+=Lane)* '}'
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Pool'
		//id=EString
		//'{'
		//    ('name' name=EString)?
		//    'lanes' '{' lanes+=Lane ( "," lanes+=Lane)* '}'
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Pool'
		public Keyword getPoolKeyword_0() { return cPoolKeyword_0; }
		
		//id=EString
		public Assignment getIdAssignment_1() { return cIdAssignment_1; }
		
		//EString
		public RuleCall getIdEStringParserRuleCall_1_0() { return cIdEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('name' name=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'name'
		public Keyword getNameKeyword_3_0() { return cNameKeyword_3_0; }
		
		//name=EString
		public Assignment getNameAssignment_3_1() { return cNameAssignment_3_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_3_1_0() { return cNameEStringParserRuleCall_3_1_0; }
		
		//'lanes'
		public Keyword getLanesKeyword_4() { return cLanesKeyword_4; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5() { return cLeftCurlyBracketKeyword_5; }
		
		//lanes+=Lane
		public Assignment getLanesAssignment_6() { return cLanesAssignment_6; }
		
		//Lane
		public RuleCall getLanesLaneParserRuleCall_6_0() { return cLanesLaneParserRuleCall_6_0; }
		
		//( "," lanes+=Lane)*
		public Group getGroup_7() { return cGroup_7; }
		
		//","
		public Keyword getCommaKeyword_7_0() { return cCommaKeyword_7_0; }
		
		//lanes+=Lane
		public Assignment getLanesAssignment_7_1() { return cLanesAssignment_7_1; }
		
		//Lane
		public RuleCall getLanesLaneParserRuleCall_7_1_0() { return cLanesLaneParserRuleCall_7_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	public class ProcessElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Process");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cProcessKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cIdAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cIdEStringParserRuleCall_1_0 = (RuleCall)cIdAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cNameKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cNameAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_3_1_0 = (RuleCall)cNameAssignment_3_1.eContents().get(0);
		private final Keyword cPoolKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cPoolAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final CrossReference cPoolPoolCrossReference_5_0 = (CrossReference)cPoolAssignment_5.eContents().get(0);
		private final RuleCall cPoolPoolEStringParserRuleCall_5_0_1 = (RuleCall)cPoolPoolCrossReference_5_0.eContents().get(1);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cTransitionsKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cTransitionsAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cTransitionsTransitionParserRuleCall_6_2_0 = (RuleCall)cTransitionsAssignment_6_2.eContents().get(0);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cTransitionsAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final RuleCall cTransitionsTransitionParserRuleCall_6_3_1_0 = (RuleCall)cTransitionsAssignment_6_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cActivitysetKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cActivitysetAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cActivitysetActivitySetParserRuleCall_7_2_0 = (RuleCall)cActivitysetAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cActivitysetAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final RuleCall cActivitysetActivitySetParserRuleCall_7_3_1_0 = (RuleCall)cActivitysetAssignment_7_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Process returns Process:
		//    'Process'
		//    id=EString
		//    '{'
		//        ('name' name=EString)?
		//        'pool' pool=[Pool|EString]
		//        ('transitions' '{' transitions+=Transition ( "," transitions+=Transition)* '}' )?
		//        ('activityset' '{' activityset+=ActivitySet ( "," activityset+=ActivitySet)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Process'
		//id=EString
		//'{'
		//    ('name' name=EString)?
		//    'pool' pool=[Pool|EString]
		//    ('transitions' '{' transitions+=Transition ( "," transitions+=Transition)* '}' )?
		//    ('activityset' '{' activityset+=ActivitySet ( "," activityset+=ActivitySet)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Process'
		public Keyword getProcessKeyword_0() { return cProcessKeyword_0; }
		
		//id=EString
		public Assignment getIdAssignment_1() { return cIdAssignment_1; }
		
		//EString
		public RuleCall getIdEStringParserRuleCall_1_0() { return cIdEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('name' name=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'name'
		public Keyword getNameKeyword_3_0() { return cNameKeyword_3_0; }
		
		//name=EString
		public Assignment getNameAssignment_3_1() { return cNameAssignment_3_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_3_1_0() { return cNameEStringParserRuleCall_3_1_0; }
		
		//'pool'
		public Keyword getPoolKeyword_4() { return cPoolKeyword_4; }
		
		//pool=[Pool|EString]
		public Assignment getPoolAssignment_5() { return cPoolAssignment_5; }
		
		//[Pool|EString]
		public CrossReference getPoolPoolCrossReference_5_0() { return cPoolPoolCrossReference_5_0; }
		
		//EString
		public RuleCall getPoolPoolEStringParserRuleCall_5_0_1() { return cPoolPoolEStringParserRuleCall_5_0_1; }
		
		//('transitions' '{' transitions+=Transition ( "," transitions+=Transition)* '}' )?
		public Group getGroup_6() { return cGroup_6; }
		
		//'transitions'
		public Keyword getTransitionsKeyword_6_0() { return cTransitionsKeyword_6_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_6_1() { return cLeftCurlyBracketKeyword_6_1; }
		
		//transitions+=Transition
		public Assignment getTransitionsAssignment_6_2() { return cTransitionsAssignment_6_2; }
		
		//Transition
		public RuleCall getTransitionsTransitionParserRuleCall_6_2_0() { return cTransitionsTransitionParserRuleCall_6_2_0; }
		
		//( "," transitions+=Transition)*
		public Group getGroup_6_3() { return cGroup_6_3; }
		
		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }
		
		//transitions+=Transition
		public Assignment getTransitionsAssignment_6_3_1() { return cTransitionsAssignment_6_3_1; }
		
		//Transition
		public RuleCall getTransitionsTransitionParserRuleCall_6_3_1_0() { return cTransitionsTransitionParserRuleCall_6_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6_4() { return cRightCurlyBracketKeyword_6_4; }
		
		//('activityset' '{' activityset+=ActivitySet ( "," activityset+=ActivitySet)* '}' )?
		public Group getGroup_7() { return cGroup_7; }
		
		//'activityset'
		public Keyword getActivitysetKeyword_7_0() { return cActivitysetKeyword_7_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }
		
		//activityset+=ActivitySet
		public Assignment getActivitysetAssignment_7_2() { return cActivitysetAssignment_7_2; }
		
		//ActivitySet
		public RuleCall getActivitysetActivitySetParserRuleCall_7_2_0() { return cActivitysetActivitySetParserRuleCall_7_2_0; }
		
		//( "," activityset+=ActivitySet)*
		public Group getGroup_7_3() { return cGroup_7_3; }
		
		//","
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }
		
		//activityset+=ActivitySet
		public Assignment getActivitysetAssignment_7_3_1() { return cActivitysetAssignment_7_3_1; }
		
		//ActivitySet
		public RuleCall getActivitysetActivitySetParserRuleCall_7_3_1_0() { return cActivitysetActivitySetParserRuleCall_7_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7_4() { return cRightCurlyBracketKeyword_7_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class MessageFlowElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.MessageFlow");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cMessageFlowAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cMessageFlowKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cSourceKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cSourceAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final CrossReference cSourceMessageFlowValidCrossReference_3_1_0 = (CrossReference)cSourceAssignment_3_1.eContents().get(0);
		private final RuleCall cSourceMessageFlowValidEStringParserRuleCall_3_1_0_1 = (RuleCall)cSourceMessageFlowValidCrossReference_3_1_0.eContents().get(1);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cTargetKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cTargetAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final CrossReference cTargetMessageFlowValidCrossReference_4_1_0 = (CrossReference)cTargetAssignment_4_1.eContents().get(0);
		private final RuleCall cTargetMessageFlowValidEStringParserRuleCall_4_1_0_1 = (RuleCall)cTargetMessageFlowValidCrossReference_4_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//MessageFlow returns MessageFlow:
		//    {MessageFlow}
		//    'MessageFlow'
		//    '{'
		//        ('source' source=[MessageFlowValid|EString])?
		//        ('target' target=[MessageFlowValid|EString])?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{MessageFlow}
		//'MessageFlow'
		//'{'
		//    ('source' source=[MessageFlowValid|EString])?
		//    ('target' target=[MessageFlowValid|EString])?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{MessageFlow}
		public Action getMessageFlowAction_0() { return cMessageFlowAction_0; }
		
		//'MessageFlow'
		public Keyword getMessageFlowKeyword_1() { return cMessageFlowKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('source' source=[MessageFlowValid|EString])?
		public Group getGroup_3() { return cGroup_3; }
		
		//'source'
		public Keyword getSourceKeyword_3_0() { return cSourceKeyword_3_0; }
		
		//source=[MessageFlowValid|EString]
		public Assignment getSourceAssignment_3_1() { return cSourceAssignment_3_1; }
		
		//[MessageFlowValid|EString]
		public CrossReference getSourceMessageFlowValidCrossReference_3_1_0() { return cSourceMessageFlowValidCrossReference_3_1_0; }
		
		//EString
		public RuleCall getSourceMessageFlowValidEStringParserRuleCall_3_1_0_1() { return cSourceMessageFlowValidEStringParserRuleCall_3_1_0_1; }
		
		//('target' target=[MessageFlowValid|EString])?
		public Group getGroup_4() { return cGroup_4; }
		
		//'target'
		public Keyword getTargetKeyword_4_0() { return cTargetKeyword_4_0; }
		
		//target=[MessageFlowValid|EString]
		public Assignment getTargetAssignment_4_1() { return cTargetAssignment_4_1; }
		
		//[MessageFlowValid|EString]
		public CrossReference getTargetMessageFlowValidCrossReference_4_1_0() { return cTargetMessageFlowValidCrossReference_4_1_0; }
		
		//EString
		public RuleCall getTargetMessageFlowValidEStringParserRuleCall_4_1_0_1() { return cTargetMessageFlowValidEStringParserRuleCall_4_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//    STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class LaneElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Lane");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cLaneAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cLaneKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cIdAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cIdEStringParserRuleCall_2_0 = (RuleCall)cIdAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cNameKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cNameAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_4_1_0 = (RuleCall)cNameAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cActivitysetKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cActivitysetAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cActivitysetActivitySetParserRuleCall_5_1_0 = (RuleCall)cActivitysetAssignment_5_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Lane returns Lane:
		//    {Lane}
		//    'Lane'
		//    id=EString
		//    '{'
		//        ('name' name=EString)?
		//        ('activityset' activityset=ActivitySet)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Lane}
		//'Lane'
		//id=EString
		//'{'
		//    ('name' name=EString)?
		//    ('activityset' activityset=ActivitySet)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Lane}
		public Action getLaneAction_0() { return cLaneAction_0; }
		
		//'Lane'
		public Keyword getLaneKeyword_1() { return cLaneKeyword_1; }
		
		//id=EString
		public Assignment getIdAssignment_2() { return cIdAssignment_2; }
		
		//EString
		public RuleCall getIdEStringParserRuleCall_2_0() { return cIdEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('name' name=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'name'
		public Keyword getNameKeyword_4_0() { return cNameKeyword_4_0; }
		
		//name=EString
		public Assignment getNameAssignment_4_1() { return cNameAssignment_4_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_4_1_0() { return cNameEStringParserRuleCall_4_1_0; }
		
		//('activityset' activityset=ActivitySet)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'activityset'
		public Keyword getActivitysetKeyword_5_0() { return cActivitysetKeyword_5_0; }
		
		//activityset=ActivitySet
		public Assignment getActivitysetAssignment_5_1() { return cActivitysetAssignment_5_1; }
		
		//ActivitySet
		public RuleCall getActivitysetActivitySetParserRuleCall_5_1_0() { return cActivitysetActivitySetParserRuleCall_5_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class ActivitySetElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.ActivitySet");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cActivitySetKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cIdAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cIdEStringParserRuleCall_1_0 = (RuleCall)cIdAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cNameKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cNameAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_3_1_0 = (RuleCall)cNameAssignment_3_1.eContents().get(0);
		private final Keyword cActivitiesKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cLeftCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cActivitiesAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cActivitiesActivityParserRuleCall_6_0 = (RuleCall)cActivitiesAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cCommaKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cActivitiesAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cActivitiesActivityParserRuleCall_7_1_0 = (RuleCall)cActivitiesAssignment_7_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//ActivitySet returns ActivitySet:
		//    'ActivitySet'
		//    id=EString
		//    '{'
		//        ('name' name=EString)?
		//        'activities' '{' activities+=Activity ( "," activities+=Activity)* '}'
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'ActivitySet'
		//id=EString
		//'{'
		//    ('name' name=EString)?
		//    'activities' '{' activities+=Activity ( "," activities+=Activity)* '}'
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'ActivitySet'
		public Keyword getActivitySetKeyword_0() { return cActivitySetKeyword_0; }
		
		//id=EString
		public Assignment getIdAssignment_1() { return cIdAssignment_1; }
		
		//EString
		public RuleCall getIdEStringParserRuleCall_1_0() { return cIdEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('name' name=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'name'
		public Keyword getNameKeyword_3_0() { return cNameKeyword_3_0; }
		
		//name=EString
		public Assignment getNameAssignment_3_1() { return cNameAssignment_3_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_3_1_0() { return cNameEStringParserRuleCall_3_1_0; }
		
		//'activities'
		public Keyword getActivitiesKeyword_4() { return cActivitiesKeyword_4; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5() { return cLeftCurlyBracketKeyword_5; }
		
		//activities+=Activity
		public Assignment getActivitiesAssignment_6() { return cActivitiesAssignment_6; }
		
		//Activity
		public RuleCall getActivitiesActivityParserRuleCall_6_0() { return cActivitiesActivityParserRuleCall_6_0; }
		
		//( "," activities+=Activity)*
		public Group getGroup_7() { return cGroup_7; }
		
		//","
		public Keyword getCommaKeyword_7_0() { return cCommaKeyword_7_0; }
		
		//activities+=Activity
		public Assignment getActivitiesAssignment_7_1() { return cActivitiesAssignment_7_1; }
		
		//Activity
		public RuleCall getActivitiesActivityParserRuleCall_7_1_0() { return cActivitiesActivityParserRuleCall_7_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	public class Activity_ImplElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Activity_Impl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cActivityAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cActivityKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cIdAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cIdEStringParserRuleCall_2_0 = (RuleCall)cIdAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cTitleKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cTitleAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cTitleEStringParserRuleCall_4_1_0 = (RuleCall)cTitleAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Activity_Impl returns Activity:
		//    {Activity}
		//    'Activity'
		//    id=EString
		//    '{'
		//        ('title' title=EString)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Activity}
		//'Activity'
		//id=EString
		//'{'
		//    ('title' title=EString)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Activity}
		public Action getActivityAction_0() { return cActivityAction_0; }
		
		//'Activity'
		public Keyword getActivityKeyword_1() { return cActivityKeyword_1; }
		
		//id=EString
		public Assignment getIdAssignment_2() { return cIdAssignment_2; }
		
		//EString
		public RuleCall getIdEStringParserRuleCall_2_0() { return cIdEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('title' title=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'title'
		public Keyword getTitleKeyword_4_0() { return cTitleKeyword_4_0; }
		
		//title=EString
		public Assignment getTitleAssignment_4_1() { return cTitleAssignment_4_1; }
		
		//EString
		public RuleCall getTitleEStringParserRuleCall_4_1_0() { return cTitleEStringParserRuleCall_4_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class BlockActivityElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.BlockActivity");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cBlockActivityAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cBlockActivityKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cIdAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cIdEStringParserRuleCall_2_0 = (RuleCall)cIdAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cTitleKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cTitleAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cTitleEStringParserRuleCall_4_1_0 = (RuleCall)cTitleAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//BlockActivity returns BlockActivity:
		//    {BlockActivity}
		//    'BlockActivity'
		//    id=EString
		//    '{'
		//        ('title' title=EString)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{BlockActivity}
		//'BlockActivity'
		//id=EString
		//'{'
		//    ('title' title=EString)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{BlockActivity}
		public Action getBlockActivityAction_0() { return cBlockActivityAction_0; }
		
		//'BlockActivity'
		public Keyword getBlockActivityKeyword_1() { return cBlockActivityKeyword_1; }
		
		//id=EString
		public Assignment getIdAssignment_2() { return cIdAssignment_2; }
		
		//EString
		public RuleCall getIdEStringParserRuleCall_2_0() { return cIdEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('title' title=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'title'
		public Keyword getTitleKeyword_4_0() { return cTitleKeyword_4_0; }
		
		//title=EString
		public Assignment getTitleAssignment_4_1() { return cTitleAssignment_4_1; }
		
		//EString
		public RuleCall getTitleEStringParserRuleCall_4_1_0() { return cTitleEStringParserRuleCall_4_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class EventElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Event");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cEventAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cEventKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cIdAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cIdEStringParserRuleCall_2_0 = (RuleCall)cIdAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cTitleKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cTitleAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cTitleEStringParserRuleCall_4_1_0 = (RuleCall)cTitleAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cTimeKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cTimeAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cTimeEventTimeEnumRuleCall_5_1_0 = (RuleCall)cTimeAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cTypeKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cTypeAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cTypeEventTypeEnumRuleCall_6_1_0 = (RuleCall)cTypeAssignment_6_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Event returns Event:
		//    {Event}
		//    'Event'
		//    id=EString
		//    '{'
		//        ('title' title=EString)?
		//        ('time' time=EventTime)?
		//        ('type' type=EventType)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Event}
		//'Event'
		//id=EString
		//'{'
		//    ('title' title=EString)?
		//    ('time' time=EventTime)?
		//    ('type' type=EventType)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Event}
		public Action getEventAction_0() { return cEventAction_0; }
		
		//'Event'
		public Keyword getEventKeyword_1() { return cEventKeyword_1; }
		
		//id=EString
		public Assignment getIdAssignment_2() { return cIdAssignment_2; }
		
		//EString
		public RuleCall getIdEStringParserRuleCall_2_0() { return cIdEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('title' title=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'title'
		public Keyword getTitleKeyword_4_0() { return cTitleKeyword_4_0; }
		
		//title=EString
		public Assignment getTitleAssignment_4_1() { return cTitleAssignment_4_1; }
		
		//EString
		public RuleCall getTitleEStringParserRuleCall_4_1_0() { return cTitleEStringParserRuleCall_4_1_0; }
		
		//('time' time=EventTime)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'time'
		public Keyword getTimeKeyword_5_0() { return cTimeKeyword_5_0; }
		
		//time=EventTime
		public Assignment getTimeAssignment_5_1() { return cTimeAssignment_5_1; }
		
		//EventTime
		public RuleCall getTimeEventTimeEnumRuleCall_5_1_0() { return cTimeEventTimeEnumRuleCall_5_1_0; }
		
		//('type' type=EventType)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'type'
		public Keyword getTypeKeyword_6_0() { return cTypeKeyword_6_0; }
		
		//type=EventType
		public Assignment getTypeAssignment_6_1() { return cTypeAssignment_6_1; }
		
		//EventType
		public RuleCall getTypeEventTypeEnumRuleCall_6_1_0() { return cTypeEventTypeEnumRuleCall_6_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class GatewayElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Gateway");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cGatewayAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cGatewayKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cIdAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cIdEStringParserRuleCall_2_0 = (RuleCall)cIdAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cTitleKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cTitleAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cTitleEStringParserRuleCall_4_1_0 = (RuleCall)cTitleAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cRuleKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cRuleAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cRuleGateRuleEnumRuleCall_5_1_0 = (RuleCall)cRuleAssignment_5_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Gateway returns Gateway:
		//    {Gateway}
		//    'Gateway'
		//    id=EString
		//    '{'
		//        ('title' title=EString)?
		//        ('rule' rule=GateRule)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Gateway}
		//'Gateway'
		//id=EString
		//'{'
		//    ('title' title=EString)?
		//    ('rule' rule=GateRule)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Gateway}
		public Action getGatewayAction_0() { return cGatewayAction_0; }
		
		//'Gateway'
		public Keyword getGatewayKeyword_1() { return cGatewayKeyword_1; }
		
		//id=EString
		public Assignment getIdAssignment_2() { return cIdAssignment_2; }
		
		//EString
		public RuleCall getIdEStringParserRuleCall_2_0() { return cIdEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('title' title=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'title'
		public Keyword getTitleKeyword_4_0() { return cTitleKeyword_4_0; }
		
		//title=EString
		public Assignment getTitleAssignment_4_1() { return cTitleAssignment_4_1; }
		
		//EString
		public RuleCall getTitleEStringParserRuleCall_4_1_0() { return cTitleEStringParserRuleCall_4_1_0; }
		
		//('rule' rule=GateRule)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'rule'
		public Keyword getRuleKeyword_5_0() { return cRuleKeyword_5_0; }
		
		//rule=GateRule
		public Assignment getRuleAssignment_5_1() { return cRuleAssignment_5_1; }
		
		//GateRule
		public RuleCall getRuleGateRuleEnumRuleCall_5_1_0() { return cRuleGateRuleEnumRuleCall_5_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class SubFlowElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.SubFlow");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cSubFlowAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cSubFlowKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cIdAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cIdEStringParserRuleCall_2_0 = (RuleCall)cIdAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cTitleKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cTitleAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cTitleEStringParserRuleCall_4_1_0 = (RuleCall)cTitleAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//SubFlow returns SubFlow:
		//    {SubFlow}
		//    'SubFlow'
		//    id=EString
		//    '{'
		//        ('title' title=EString)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{SubFlow}
		//'SubFlow'
		//id=EString
		//'{'
		//    ('title' title=EString)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{SubFlow}
		public Action getSubFlowAction_0() { return cSubFlowAction_0; }
		
		//'SubFlow'
		public Keyword getSubFlowKeyword_1() { return cSubFlowKeyword_1; }
		
		//id=EString
		public Assignment getIdAssignment_2() { return cIdAssignment_2; }
		
		//EString
		public RuleCall getIdEStringParserRuleCall_2_0() { return cIdEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('title' title=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'title'
		public Keyword getTitleKeyword_4_0() { return cTitleKeyword_4_0; }
		
		//title=EString
		public Assignment getTitleAssignment_4_1() { return cTitleAssignment_4_1; }
		
		//EString
		public RuleCall getTitleEStringParserRuleCall_4_1_0() { return cTitleEStringParserRuleCall_4_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class TransitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Transition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTransitionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cConditionKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cConditionAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cConditionEStringParserRuleCall_2_1_0 = (RuleCall)cConditionAssignment_2_1.eContents().get(0);
		private final Keyword cSourceKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cSourceAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cSourceTransitionValidCrossReference_4_0 = (CrossReference)cSourceAssignment_4.eContents().get(0);
		private final RuleCall cSourceTransitionValidEStringParserRuleCall_4_0_1 = (RuleCall)cSourceTransitionValidCrossReference_4_0.eContents().get(1);
		private final Keyword cTargetKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cTargetAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final CrossReference cTargetTransitionValidCrossReference_6_0 = (CrossReference)cTargetAssignment_6.eContents().get(0);
		private final RuleCall cTargetTransitionValidEStringParserRuleCall_6_0_1 = (RuleCall)cTargetTransitionValidCrossReference_6_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Transition returns Transition:
		//    'Transition'
		//    '{'
		//        ('condition' condition=EString)?
		//        'source' source=[TransitionValid|EString]
		//        'target' target=[TransitionValid|EString]
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Transition'
		//'{'
		//    ('condition' condition=EString)?
		//    'source' source=[TransitionValid|EString]
		//    'target' target=[TransitionValid|EString]
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Transition'
		public Keyword getTransitionKeyword_0() { return cTransitionKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//('condition' condition=EString)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'condition'
		public Keyword getConditionKeyword_2_0() { return cConditionKeyword_2_0; }
		
		//condition=EString
		public Assignment getConditionAssignment_2_1() { return cConditionAssignment_2_1; }
		
		//EString
		public RuleCall getConditionEStringParserRuleCall_2_1_0() { return cConditionEStringParserRuleCall_2_1_0; }
		
		//'source'
		public Keyword getSourceKeyword_3() { return cSourceKeyword_3; }
		
		//source=[TransitionValid|EString]
		public Assignment getSourceAssignment_4() { return cSourceAssignment_4; }
		
		//[TransitionValid|EString]
		public CrossReference getSourceTransitionValidCrossReference_4_0() { return cSourceTransitionValidCrossReference_4_0; }
		
		//EString
		public RuleCall getSourceTransitionValidEStringParserRuleCall_4_0_1() { return cSourceTransitionValidEStringParserRuleCall_4_0_1; }
		
		//'target'
		public Keyword getTargetKeyword_5() { return cTargetKeyword_5; }
		
		//target=[TransitionValid|EString]
		public Assignment getTargetAssignment_6() { return cTargetAssignment_6; }
		
		//[TransitionValid|EString]
		public CrossReference getTargetTransitionValidCrossReference_6_0() { return cTargetTransitionValidCrossReference_6_0; }
		
		//EString
		public RuleCall getTargetTransitionValidEStringParserRuleCall_6_0_1() { return cTargetTransitionValidEStringParserRuleCall_6_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	
	public class EventTimeElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.EventTime");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cSTARTEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cSTARTSTARTKeyword_0_0 = (Keyword)cSTARTEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cINTERMEDIATEEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cINTERMEDIATEINTERMEDIATEKeyword_1_0 = (Keyword)cINTERMEDIATEEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cENDEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cENDENDKeyword_2_0 = (Keyword)cENDEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum EventTime returns EventTime:
		//                START = 'START' | INTERMEDIATE = 'INTERMEDIATE' | END = 'END';
		public EnumRule getRule() { return rule; }
		
		//START = 'START' | INTERMEDIATE = 'INTERMEDIATE' | END = 'END'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//START = 'START'
		public EnumLiteralDeclaration getSTARTEnumLiteralDeclaration_0() { return cSTARTEnumLiteralDeclaration_0; }
		
		//'START'
		public Keyword getSTARTSTARTKeyword_0_0() { return cSTARTSTARTKeyword_0_0; }
		
		//INTERMEDIATE = 'INTERMEDIATE'
		public EnumLiteralDeclaration getINTERMEDIATEEnumLiteralDeclaration_1() { return cINTERMEDIATEEnumLiteralDeclaration_1; }
		
		//'INTERMEDIATE'
		public Keyword getINTERMEDIATEINTERMEDIATEKeyword_1_0() { return cINTERMEDIATEINTERMEDIATEKeyword_1_0; }
		
		//END = 'END'
		public EnumLiteralDeclaration getENDEnumLiteralDeclaration_2() { return cENDEnumLiteralDeclaration_2; }
		
		//'END'
		public Keyword getENDENDKeyword_2_0() { return cENDENDKeyword_2_0; }
	}
	public class EventTypeElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.EventType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cNONEEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cNONENONEKeyword_0_0 = (Keyword)cNONEEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cMESSAGEEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cMESSAGEMESSAGEKeyword_1_0 = (Keyword)cMESSAGEEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cEROREnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cERORERORKeyword_2_0 = (Keyword)cEROREnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cRULEEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cRULERULEKeyword_3_0 = (Keyword)cRULEEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cTIMEREnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cTIMERTIMERKeyword_4_0 = (Keyword)cTIMEREnumLiteralDeclaration_4.eContents().get(0);
		
		//enum EventType returns EventType:
		//                NONE = 'NONE' | MESSAGE = 'MESSAGE' | EROR = 'EROR' | RULE = 'RULE' | TIMER = 'TIMER';
		public EnumRule getRule() { return rule; }
		
		//NONE = 'NONE' | MESSAGE = 'MESSAGE' | EROR = 'EROR' | RULE = 'RULE' | TIMER = 'TIMER'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//NONE = 'NONE'
		public EnumLiteralDeclaration getNONEEnumLiteralDeclaration_0() { return cNONEEnumLiteralDeclaration_0; }
		
		//'NONE'
		public Keyword getNONENONEKeyword_0_0() { return cNONENONEKeyword_0_0; }
		
		//MESSAGE = 'MESSAGE'
		public EnumLiteralDeclaration getMESSAGEEnumLiteralDeclaration_1() { return cMESSAGEEnumLiteralDeclaration_1; }
		
		//'MESSAGE'
		public Keyword getMESSAGEMESSAGEKeyword_1_0() { return cMESSAGEMESSAGEKeyword_1_0; }
		
		//EROR = 'EROR'
		public EnumLiteralDeclaration getEROREnumLiteralDeclaration_2() { return cEROREnumLiteralDeclaration_2; }
		
		//'EROR'
		public Keyword getERORERORKeyword_2_0() { return cERORERORKeyword_2_0; }
		
		//RULE = 'RULE'
		public EnumLiteralDeclaration getRULEEnumLiteralDeclaration_3() { return cRULEEnumLiteralDeclaration_3; }
		
		//'RULE'
		public Keyword getRULERULEKeyword_3_0() { return cRULERULEKeyword_3_0; }
		
		//TIMER = 'TIMER'
		public EnumLiteralDeclaration getTIMEREnumLiteralDeclaration_4() { return cTIMEREnumLiteralDeclaration_4; }
		
		//'TIMER'
		public Keyword getTIMERTIMERKeyword_4_0() { return cTIMERTIMERKeyword_4_0; }
	}
	public class GateRuleElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.GateRule");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cXOREnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cXORXORKeyword_0_0 = (Keyword)cXOREnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cOREnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cORORKeyword_1_0 = (Keyword)cOREnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cANDEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cANDANDKeyword_2_0 = (Keyword)cANDEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum GateRule returns GateRule:
		//                XOR = 'XOR' | OR = 'OR' | AND = 'AND';
		public EnumRule getRule() { return rule; }
		
		//XOR = 'XOR' | OR = 'OR' | AND = 'AND'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//XOR = 'XOR'
		public EnumLiteralDeclaration getXOREnumLiteralDeclaration_0() { return cXOREnumLiteralDeclaration_0; }
		
		//'XOR'
		public Keyword getXORXORKeyword_0_0() { return cXORXORKeyword_0_0; }
		
		//OR = 'OR'
		public EnumLiteralDeclaration getOREnumLiteralDeclaration_1() { return cOREnumLiteralDeclaration_1; }
		
		//'OR'
		public Keyword getORORKeyword_1_0() { return cORORKeyword_1_0; }
		
		//AND = 'AND'
		public EnumLiteralDeclaration getANDEnumLiteralDeclaration_2() { return cANDEnumLiteralDeclaration_2; }
		
		//'AND'
		public Keyword getANDANDKeyword_2_0() { return cANDANDKeyword_2_0; }
	}
	
	private final XpdlRootElements pXpdlRoot;
	private final MessageFlowValidElements pMessageFlowValid;
	private final ActivityElements pActivity;
	private final TransitionValidElements pTransitionValid;
	private final PoolElements pPool;
	private final ProcessElements pProcess;
	private final MessageFlowElements pMessageFlow;
	private final EStringElements pEString;
	private final LaneElements pLane;
	private final ActivitySetElements pActivitySet;
	private final Activity_ImplElements pActivity_Impl;
	private final BlockActivityElements pBlockActivity;
	private final EventElements pEvent;
	private final GatewayElements pGateway;
	private final SubFlowElements pSubFlow;
	private final EventTimeElements eEventTime;
	private final EventTypeElements eEventType;
	private final GateRuleElements eGateRule;
	private final TransitionElements pTransition;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public MyDslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pXpdlRoot = new XpdlRootElements();
		this.pMessageFlowValid = new MessageFlowValidElements();
		this.pActivity = new ActivityElements();
		this.pTransitionValid = new TransitionValidElements();
		this.pPool = new PoolElements();
		this.pProcess = new ProcessElements();
		this.pMessageFlow = new MessageFlowElements();
		this.pEString = new EStringElements();
		this.pLane = new LaneElements();
		this.pActivitySet = new ActivitySetElements();
		this.pActivity_Impl = new Activity_ImplElements();
		this.pBlockActivity = new BlockActivityElements();
		this.pEvent = new EventElements();
		this.pGateway = new GatewayElements();
		this.pSubFlow = new SubFlowElements();
		this.eEventTime = new EventTimeElements();
		this.eEventType = new EventTypeElements();
		this.eGateRule = new GateRuleElements();
		this.pTransition = new TransitionElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.mydsl.MyDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//XpdlRoot returns XpdlRoot:
	//    {XpdlRoot}
	//    'XpdlRoot'
	//    id=EString
	//    '{'
	//        ('diagramName' diagramName=EString)?
	//        ('pools' '{' pools+=Pool ( "," pools+=Pool)* '}' )?
	//        ('process' '{' process+=Process ( "," process+=Process)* '}' )?
	//        ('messageflows' '{' messageflows+=MessageFlow ( "," messageflows+=MessageFlow)* '}' )?
	//    '}';
	public XpdlRootElements getXpdlRootAccess() {
		return pXpdlRoot;
	}
	
	public ParserRule getXpdlRootRule() {
		return getXpdlRootAccess().getRule();
	}
	
	//MessageFlowValid returns MessageFlowValid:
	//    Pool | Activity_Impl | BlockActivity | Event | Gateway | SubFlow;
	public MessageFlowValidElements getMessageFlowValidAccess() {
		return pMessageFlowValid;
	}
	
	public ParserRule getMessageFlowValidRule() {
		return getMessageFlowValidAccess().getRule();
	}
	
	//Activity returns Activity:
	//    Activity_Impl | BlockActivity | Event | Gateway | SubFlow;
	public ActivityElements getActivityAccess() {
		return pActivity;
	}
	
	public ParserRule getActivityRule() {
		return getActivityAccess().getRule();
	}
	
	//TransitionValid returns TransitionValid:
	//    Activity_Impl | BlockActivity | Event | Gateway | SubFlow;
	public TransitionValidElements getTransitionValidAccess() {
		return pTransitionValid;
	}
	
	public ParserRule getTransitionValidRule() {
		return getTransitionValidAccess().getRule();
	}
	
	//Pool returns Pool:
	//    'Pool'
	//    id=EString
	//    '{'
	//        ('name' name=EString)?
	//        'lanes' '{' lanes+=Lane ( "," lanes+=Lane)* '}'
	//    '}';
	public PoolElements getPoolAccess() {
		return pPool;
	}
	
	public ParserRule getPoolRule() {
		return getPoolAccess().getRule();
	}
	
	//Process returns Process:
	//    'Process'
	//    id=EString
	//    '{'
	//        ('name' name=EString)?
	//        'pool' pool=[Pool|EString]
	//        ('transitions' '{' transitions+=Transition ( "," transitions+=Transition)* '}' )?
	//        ('activityset' '{' activityset+=ActivitySet ( "," activityset+=ActivitySet)* '}' )?
	//    '}';
	public ProcessElements getProcessAccess() {
		return pProcess;
	}
	
	public ParserRule getProcessRule() {
		return getProcessAccess().getRule();
	}
	
	//MessageFlow returns MessageFlow:
	//    {MessageFlow}
	//    'MessageFlow'
	//    '{'
	//        ('source' source=[MessageFlowValid|EString])?
	//        ('target' target=[MessageFlowValid|EString])?
	//    '}';
	public MessageFlowElements getMessageFlowAccess() {
		return pMessageFlow;
	}
	
	public ParserRule getMessageFlowRule() {
		return getMessageFlowAccess().getRule();
	}
	
	//EString returns ecore::EString:
	//    STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//Lane returns Lane:
	//    {Lane}
	//    'Lane'
	//    id=EString
	//    '{'
	//        ('name' name=EString)?
	//        ('activityset' activityset=ActivitySet)?
	//    '}';
	public LaneElements getLaneAccess() {
		return pLane;
	}
	
	public ParserRule getLaneRule() {
		return getLaneAccess().getRule();
	}
	
	//ActivitySet returns ActivitySet:
	//    'ActivitySet'
	//    id=EString
	//    '{'
	//        ('name' name=EString)?
	//        'activities' '{' activities+=Activity ( "," activities+=Activity)* '}'
	//    '}';
	public ActivitySetElements getActivitySetAccess() {
		return pActivitySet;
	}
	
	public ParserRule getActivitySetRule() {
		return getActivitySetAccess().getRule();
	}
	
	//Activity_Impl returns Activity:
	//    {Activity}
	//    'Activity'
	//    id=EString
	//    '{'
	//        ('title' title=EString)?
	//    '}';
	public Activity_ImplElements getActivity_ImplAccess() {
		return pActivity_Impl;
	}
	
	public ParserRule getActivity_ImplRule() {
		return getActivity_ImplAccess().getRule();
	}
	
	//BlockActivity returns BlockActivity:
	//    {BlockActivity}
	//    'BlockActivity'
	//    id=EString
	//    '{'
	//        ('title' title=EString)?
	//    '}';
	public BlockActivityElements getBlockActivityAccess() {
		return pBlockActivity;
	}
	
	public ParserRule getBlockActivityRule() {
		return getBlockActivityAccess().getRule();
	}
	
	//Event returns Event:
	//    {Event}
	//    'Event'
	//    id=EString
	//    '{'
	//        ('title' title=EString)?
	//        ('time' time=EventTime)?
	//        ('type' type=EventType)?
	//    '}';
	public EventElements getEventAccess() {
		return pEvent;
	}
	
	public ParserRule getEventRule() {
		return getEventAccess().getRule();
	}
	
	//Gateway returns Gateway:
	//    {Gateway}
	//    'Gateway'
	//    id=EString
	//    '{'
	//        ('title' title=EString)?
	//        ('rule' rule=GateRule)?
	//    '}';
	public GatewayElements getGatewayAccess() {
		return pGateway;
	}
	
	public ParserRule getGatewayRule() {
		return getGatewayAccess().getRule();
	}
	
	//SubFlow returns SubFlow:
	//    {SubFlow}
	//    'SubFlow'
	//    id=EString
	//    '{'
	//        ('title' title=EString)?
	//    '}';
	public SubFlowElements getSubFlowAccess() {
		return pSubFlow;
	}
	
	public ParserRule getSubFlowRule() {
		return getSubFlowAccess().getRule();
	}
	
	//enum EventTime returns EventTime:
	//                START = 'START' | INTERMEDIATE = 'INTERMEDIATE' | END = 'END';
	public EventTimeElements getEventTimeAccess() {
		return eEventTime;
	}
	
	public EnumRule getEventTimeRule() {
		return getEventTimeAccess().getRule();
	}
	
	//enum EventType returns EventType:
	//                NONE = 'NONE' | MESSAGE = 'MESSAGE' | EROR = 'EROR' | RULE = 'RULE' | TIMER = 'TIMER';
	public EventTypeElements getEventTypeAccess() {
		return eEventType;
	}
	
	public EnumRule getEventTypeRule() {
		return getEventTypeAccess().getRule();
	}
	
	//enum GateRule returns GateRule:
	//                XOR = 'XOR' | OR = 'OR' | AND = 'AND';
	public GateRuleElements getGateRuleAccess() {
		return eGateRule;
	}
	
	public EnumRule getGateRuleRule() {
		return getGateRuleAccess().getRule();
	}
	
	//Transition returns Transition:
	//    'Transition'
	//    '{'
	//        ('condition' condition=EString)?
	//        'source' source=[TransitionValid|EString]
	//        'target' target=[TransitionValid|EString]
	//    '}';
	public TransitionElements getTransitionAccess() {
		return pTransition;
	}
	
	public ParserRule getTransitionRule() {
		return getTransitionAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
